baseURL: https://chao-cui.github.io/

theme: charlolamode

menu:
    main:
        # - name: Contact
        #   url: /contact/
        #   weight: 30

        - name: Games
          url: /games/
          weight: 30

        - name: Toys
          url: /toys/
          weight: 31

        # - name: Articles
        #   url: /articles/
        #   weight: 20

        - name: About Me
          url: /about/
          weight: 32

        # - name: new Tab
        #   url: /newtab/
        #   weight: defines order of tabs
   


params:
    author: #Author's Name

    defaultTheme: auto
    disableThemeToggle: false
    ShowShareButtons: false
    ShowReadingTime: false
    displayFullLangName: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: false
    ShowToc: false

    profileMode:
        # Disable to populate home page with 'mainSections' content
        enabled: true
        title: Chao Cui
        description: |
          Hi. I make games.  
          Glad to meet you here.

        imageUrl: "/images/animal-planner/icon.png"
        imageTitle: image
        imageWidth: 120
        imageHeight: 120

        buttons:
        #     - name: Don't click me
        #       url: https://www.youtube.com/watch?v=dQw4w9WgXcQ

    mainSections:
      # - articles
      - games
      - toys

    socialIcons:
    #     - name: buymeacoffee
    #       url: "https://ko-fi.com/heycharlola"
    #     - name: github
    #       url: "https://github.com/charlola"


      # add more social icons. find more in svg.html file
      # - name: youtube
      #   url: yoururl
      - name: twitter
        url: "https://twitter.com/lunarDust_"
      # - name: facebook
      #   url: yoururl

      - name: linkedin
        url: "https://www.linkedin.com/in/chao-cui-15920a273/"


    # change favicon in images folder (icon for web tab)
    assets:
          favicon: "/images/favicon.ico"
          favicon16x16: "/images/favicon-16x16.png"
          favicon32x32: "/images/favicon-32x32.png"
          apple_touch_icon: "/images/apple-touch-icon.png"
          safari_pinned_tab: "/images/apple-touch-icon.png"



enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true

minify:
    disableXML: true

# markup:
#   markup.goldmark:
#     markup.goldmark.renderer:
#       unsafe: true

# services:
#   instagram:
#     accessToken: xxx
